#######################################
#####                             #####
#####           Daytime           #####
#####                             #####
#######################################

# written by mfnalex / JEFF Media GbR

#######################################
#####         Permissions         #####
#######################################

# daytime.admin    Allows to use the /daytime command

#######################################
#####           Commands          #####
#######################################

# /daytime         Reloads the configuration file

#######################################
#####        Configuration        #####
#######################################

# Changes the day/night length per world. Values are set in minutes.
# Vanilla default is 10 minutes per day and 10 minutes per night.
# If a world is not set, its time will not be changed.
# You can also use fractional values, e.g. 0.5 = 30 seconds
worlds:
  world: # Sets the day and night length in "world" to 10 minutes each (default)
    daytime: 10
    nighttime: 10
  example_world: # Sets the day length in "example_world" to 15 minutes, and the night length to 5 minutes
    daytime: 15
    nighttime: 5